// GENERATED by tools/export-data.mjs from the web app's src/data/kana.js. Do not edit by hand.
// Row = 行 (consonant row), column = 段 (vowel column). null marks a gap in the 11 x 5 grid.
package app.kanapon.data

internal val HIRAGANA_ROWS: List<List<Kana?>> =
    listOf(
        listOf(Kana("あ", "a", 3), Kana("い", "i", 2), Kana("う", "u", 2), Kana("え", "e", 2), Kana("お", "o", 3)),
        listOf(Kana("か", "ka", 3), Kana("き", "ki", 4), Kana("く", "ku", 1), Kana("け", "ke", 3), Kana("こ", "ko", 2)),
        listOf(Kana("さ", "sa", 3), Kana("し", "shi", 1), Kana("す", "su", 2), Kana("せ", "se", 3), Kana("そ", "so", 1)),
        listOf(Kana("た", "ta", 4), Kana("ち", "chi", 2), Kana("つ", "tsu", 1), Kana("て", "te", 1), Kana("と", "to", 2)),
        listOf(Kana("な", "na", 4), Kana("に", "ni", 3), Kana("ぬ", "nu", 2), Kana("ね", "ne", 2), Kana("の", "no", 1)),
        listOf(Kana("は", "ha", 3), Kana("ひ", "hi", 1), Kana("ふ", "fu", 4), Kana("へ", "he", 1), Kana("ほ", "ho", 4)),
        listOf(Kana("ま", "ma", 3), Kana("み", "mi", 2), Kana("む", "mu", 3), Kana("め", "me", 2), Kana("も", "mo", 3)),
        listOf(Kana("や", "ya", 3), null, Kana("ゆ", "yu", 2), null, Kana("よ", "yo", 2)),
        listOf(Kana("ら", "ra", 2), Kana("り", "ri", 2), Kana("る", "ru", 1), Kana("れ", "re", 2), Kana("ろ", "ro", 1)),
        listOf(Kana("わ", "wa", 2), null, null, null, Kana("を", "wo", 3)),
        listOf(Kana("ん", "n", 1), null, null, null, null)
    )

internal val KATAKANA_ROWS: List<List<Kana?>> =
    listOf(
        listOf(Kana("ア", "a", 2), Kana("イ", "i", 2), Kana("ウ", "u", 3), Kana("エ", "e", 3), Kana("オ", "o", 3)),
        listOf(Kana("カ", "ka", 2), Kana("キ", "ki", 3), Kana("ク", "ku", 2), Kana("ケ", "ke", 3), Kana("コ", "ko", 2)),
        listOf(Kana("サ", "sa", 3), Kana("シ", "shi", 3), Kana("ス", "su", 2), Kana("セ", "se", 2), Kana("ソ", "so", 2)),
        listOf(Kana("タ", "ta", 3), Kana("チ", "chi", 3), Kana("ツ", "tsu", 3), Kana("テ", "te", 3), Kana("ト", "to", 2)),
        listOf(Kana("ナ", "na", 2), Kana("ニ", "ni", 2), Kana("ヌ", "nu", 2), Kana("ネ", "ne", 4), Kana("ノ", "no", 1)),
        listOf(Kana("ハ", "ha", 2), Kana("ヒ", "hi", 2), Kana("フ", "fu", 1), Kana("ヘ", "he", 1), Kana("ホ", "ho", 4)),
        listOf(Kana("マ", "ma", 2), Kana("ミ", "mi", 3), Kana("ム", "mu", 2), Kana("メ", "me", 2), Kana("モ", "mo", 3)),
        listOf(Kana("ヤ", "ya", 2), null, Kana("ユ", "yu", 2), null, Kana("ヨ", "yo", 3)),
        listOf(Kana("ラ", "ra", 2), Kana("リ", "ri", 2), Kana("ル", "ru", 2), Kana("レ", "re", 1), Kana("ロ", "ro", 3)),
        listOf(Kana("ワ", "wa", 2), null, null, null, Kana("ヲ", "wo", 3)),
        listOf(Kana("ン", "n", 2), null, null, null, null)
    )
