// GENERATED by tools/export-data.mjs from the web app's src/data/klee.js and src/data/strokes.js.
// Where Klee One sits in KanjiVG's 109 box. Every model glyph is drawn at this placement so it lies on
// top of the scoring reference in klee-strokes.json; change these only together with that file.
package app.kanapon.data

const val VIEWBOX = 109f
const val STROKE_WIDTH = 3f
const val KLEE_SIZE = 109f
const val KLEE_X = 54.5f
const val KLEE_BASELINE = 91.7f
