#!/usr/bin/env node
/* Copies the web app's data into this project, so the two never drift.
 *
 *   node tools/export-data.mjs [path/to/kanapon]     (default: ../kanapon)
 *
 * Writes, all GENERATED — do not edit by hand:
 *   app/src/main/java/app/kanapon/data/KanaTables.kt   gojūon tables from src/data/kana.js
 *   app/src/main/java/app/kanapon/data/KleePlacement.kt  src/data/klee.js + strokes.js constants
 *   app/src/main/assets/data/strokes.json              KanjiVG stroke order (CC BY-SA 3.0)
 *   app/src/main/assets/data/klee-strokes.json         scoring reference (CC BY-SA 3.0)
 *   app/src/main/assets/glyphs/<hex>.svg               Klee One outlines on their ruling (OFL)
 *   app/src/main/assets/licenses/*.txt                 licence texts the Credits page shows
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const WEB = path.resolve(process.argv[2] || path.join(ROOT, '..', 'kanapon'));
const MAIN = path.join(ROOT, 'app', 'src', 'main');
const ASSETS = path.join(MAIN, 'assets');
const PKG = path.join(MAIN, 'java', 'app', 'kanapon', 'data');

const load = rel => import(pathToFileURL(path.join(WEB, rel)).href);
const kana = await load('src/data/kana.js');
const strokes = await load('src/data/strokes.js');
const klee = await load('src/data/klee-strokes.js');
const placement = await load('src/data/klee.js');

const write = (file, text) => {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, text);
  console.log('wrote', path.relative(ROOT, file));
};

const KANJIVG =
  'Stroke data from KanjiVG, Copyright (C) 2009/2010/2011 Ulrich Apel, https://kanjivg.tagaini.net, ' +
  'distributed under the Creative Commons Attribution-Share Alike 3.0 licence (assets/licenses/KanjiVG-CC-BY-SA-3.0.txt). ' +
  'This file is a derivative of KanjiVG and stays under CC BY-SA 3.0.';

/* ---- Kotlin tables ---- */
const kt = s => `"${s}"`;
const table = rows =>
  rows
    .map(row => '        listOf(' + row.map(c => (c ? `Kana(${kt(c[0])}, ${kt(c[1])}, ${c[2]})` : 'null')).join(', ') + '),')
    .join('\n');
write(
  path.join(PKG, 'KanaTables.kt'),
  `// GENERATED by tools/export-data.mjs from the web app's src/data/kana.js. Do not edit by hand.
// Row = 行 (consonant row), column = 段 (vowel column). null marks a gap in the 11 x 5 grid.
package app.kanapon.data

internal val HIRAGANA_ROWS: List<List<Kana?>> =
    listOf(
${table(kana.HIRAGANA)}
    )

internal val KATAKANA_ROWS: List<List<Kana?>> =
    listOf(
${table(kana.KATAKANA)}
    )
`,
);
write(
  path.join(PKG, 'KleePlacement.kt'),
  `// GENERATED by tools/export-data.mjs from the web app's src/data/klee.js and src/data/strokes.js.
// Where Klee One sits in KanjiVG's 109 box. Every model glyph is drawn at this placement so it lies on
// top of the scoring reference in klee-strokes.json; change these only together with that file.
package app.kanapon.data

const val VIEWBOX = ${strokes.VIEWBOX}f
const val STROKE_WIDTH = ${strokes.STROKE_WIDTH}f
const val KLEE_SIZE = ${placement.KLEE_SIZE}f
const val KLEE_X = ${placement.KLEE_X}f
const val KLEE_BASELINE = ${placement.KLEE_BASELINE}f
`,
);

/* ---- JSON assets ---- */
write(
  path.join(ASSETS, 'data', 'strokes.json'),
  JSON.stringify({ _licence: KANJIVG, strokes: strokes.STROKES }) + '\n',
);
write(
  path.join(ASSETS, 'data', 'klee-strokes.json'),
  JSON.stringify({
    _licence: KANJIVG + ' Shapes from Klee One, (c) Fontworks Inc., SIL Open Font License 1.1.',
    strokes: Object.fromEntries(Object.entries(klee.KLEE_STROKES).map(([k, v]) => [k, v.d])),
  }) + '\n',
);

/* ---- glyph outlines ---- */
const glyphs = path.join(ASSETS, 'glyphs');
fs.rmSync(glyphs, { recursive: true, force: true });
fs.mkdirSync(glyphs, { recursive: true });
let n = 0;
for (const f of fs.readdirSync(path.join(WEB, 'public', 'glyphs'))) {
  if (!f.endsWith('.svg')) continue;
  fs.copyFileSync(path.join(WEB, 'public', 'glyphs', f), path.join(glyphs, f));
  n++;
}
console.log(`copied ${n} glyphs`);
if (n !== kana.TOTAL) throw new Error(`expected ${kana.TOTAL} glyphs, found ${n}`);

/* ---- licences ---- */
const lic = path.join(ASSETS, 'licenses');
fs.mkdirSync(lic, { recursive: true });
fs.copyFileSync(path.join(WEB, 'public', 'licenses', 'KanjiVG-CC-BY-SA-3.0.txt'), path.join(lic, 'KanjiVG-CC-BY-SA-3.0.txt'));
for (const f of ['KleeOne-OFL.txt', 'ZenKakuGothicNew-OFL.txt']) {
  fs.copyFileSync(path.join(WEB, 'public', 'fonts', f), path.join(lic, f));
}
const pf = path.join(lic, 'perfect-freehand-MIT.txt');
if (!fs.existsSync(pf)) {
  const res = await fetch('https://raw.githubusercontent.com/steveruizok/perfect-freehand/main/LICENSE');
  if (!res.ok) throw new Error(`perfect-freehand licence: HTTP ${res.status}`);
  write(pf, await res.text());
}
